# Local dev workflow for face-capture.
#
# Typical first-time setup:
#   cp .env.example .env       # then edit API_KEY
#   make install               # python + node deps
#   make up                    # start Postgres
#   make migrate               # apply schema
#   make dev                   # API + SPA in one terminal
#
# After that, `make dev` is the only command you need day-to-day.

SHELL := /bin/bash
.DEFAULT_GOAL := help

# --- Config ----------------------------------------------------------------
VENV        := .venv
PY          := $(VENV)/bin/python
PIP         := $(VENV)/bin/pip
UVICORN     := $(VENV)/bin/uvicorn
ALEMBIC     := $(VENV)/bin/alembic
COMPOSE     := docker compose
API_PORT    := 8000
WEB_PORT    := 5173

# --- Help ------------------------------------------------------------------
.PHONY: help
help: ## Show this help.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# --- Setup -----------------------------------------------------------------
.PHONY: venv
venv: ## Create the Python venv if missing.
	@test -d $(VENV) || python3 -m venv $(VENV)

.PHONY: install
install: venv ## Install Python and Node deps.
	$(PIP) install --upgrade pip
	$(PIP) install -r requirements.txt
	cd web && npm ci

# --- Postgres --------------------------------------------------------------
.PHONY: up
up: ## Start Postgres (docker compose).
	$(COMPOSE) up -d postgres
	@echo "Waiting for Postgres to become healthy..."
	@until [ "$$($(COMPOSE) ps --format json postgres | grep -o '"Health":"healthy"')" = '"Health":"healthy"' ]; do sleep 1; done
	@echo "Postgres is ready."

.PHONY: down
down: ## Stop Postgres (keeps data volume).
	$(COMPOSE) down

.PHONY: psql
psql: ## Open a psql shell against the dev database.
	$(COMPOSE) exec postgres psql -U facecap -d facecap

.PHONY: nuke-db
nuke-db: ## DESTROY the local Postgres volume. Confirmation required.
	@read -p "This deletes ALL local Postgres data. Type 'yes' to continue: " ans && [ "$$ans" = "yes" ]
	$(COMPOSE) down -v

# --- Migrations ------------------------------------------------------------
.PHONY: migrate
migrate: ## Apply migrations to head.
	$(ALEMBIC) upgrade head

.PHONY: migration
migration: ## Create a new autogenerated migration. Usage: make migration name="add foo"
	@test -n "$(name)" || (echo 'usage: make migration name="describe the change"' && exit 1)
	$(ALEMBIC) revision --autogenerate -m "$(name)"

.PHONY: downgrade
downgrade: ## Roll back one migration step.
	$(ALEMBIC) downgrade -1

# --- Run -------------------------------------------------------------------
.PHONY: api
api: ## Run the FastAPI service with autoreload.
	$(UVICORN) app.main:app --host 0.0.0.0 --port $(API_PORT) --reload

.PHONY: web
web: ## Run the Vite SPA dev server.
	cd web && npm run dev

# `make dev` runs api + web concurrently. We background the API, foreground
# the web server, and trap signals so a Ctrl-C kills both.
.PHONY: dev
dev: ## Run API + SPA together. Ctrl-C stops both.
	@set -m; \
	  trap 'kill 0' INT TERM EXIT; \
	  $(UVICORN) app.main:app --host 0.0.0.0 --port $(API_PORT) --reload & \
	  cd web && npm run dev; \
	  wait

# --- Frontend build / checks ----------------------------------------------
.PHONY: web-build
web-build: ## Production build of the SPA into web/dist.
	cd web && npm run build

.PHONY: typecheck
typecheck: ## TypeScript typecheck on the frontend.
	cd web && npm run typecheck

# --- Docker (parity with Railway) -----------------------------------------
.PHONY: docker-build
docker-build: ## Build the production image locally.
	docker build -t face-capture:dev .

.PHONY: docker-run
docker-run: ## Run the production image against the local Postgres + .env.
	docker run --rm -p 8000:8000 \
	  --env-file .env \
	  --add-host=host.docker.internal:host-gateway \
	  -e DATABASE_URL=postgresql+asyncpg://facecap:facecap@host.docker.internal:5432/facecap \
	  face-capture:dev

# --- Cleanup ---------------------------------------------------------------
.PHONY: clean
clean: ## Remove local storage + job working dirs (not the database).
	rm -rf _storage jobs web/dist
